### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by ghost** [alexburlton/pocket-scat#6]
Current blockers:

 - `flutter_driver` isn't there yet, and trying to bump other dependencies results in annoying clashes like:
 
 ```
 $ flutter pub get
Because flutter_launcher_icons 0.9.0 depends on args 2.0.0 and every version of flutter_driver from sdk depends on args 1.6.0, flutter_launcher_icons 0.9.0 is incompatible with flutter_driver from sdk.                                                                               
So, because pocket_scat depends on both flutter_driver any from sdk and flutter_launcher_icons 0.9.0, version solving failed.
Running "flutter pub get" in pocket_scat...                             
pub get failed (1; So, because pocket_scat depends on both flutter_driver any from sdk and flutter_launcher_icons 0.9.0, version solving
failed.)
 ```
 
 - Mockito pain: I played around a bit with their suggested workarounds (see [here](https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md)), but the auto-generated code just didn't work. Tests still failed, and to top things off the generated file also violated various linter rules.

**Comment by alyssaruth** [comment]
Gonna look at replacing `flutter_driver` with `integration_test` to resolve the first issue. And then maybe `mocktail` over `mockito` for the second.

**Comment by pinkasey** [comment]
`integration_test` depends on `flutter_driver`, so you get the same problem (I've just checked)
